networks:
  server-bridge:
    driver: bridge

services:
  py-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: final
    image: "riyad/python-fast-app:v2"
    container_name: py-app
    restart: always
    ports:
      - "${APP_PORT}:80"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    env_file:
      - .env
    volumes:
      - ./database.py:/pyapp/database.py
      - ./main.py:/pyapp/main.py
    networks:
      - server-bridge
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: "mysql:8.0.29-debian"
    container_name: "py-mysql"
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./movies.sql:/docker-entrypoint-initdb.d/movies.sql
    networks:
      - server-bridge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    container_name: test-runner
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      py-app:
        condition: service_started
    networks:
      - server-bridge
    command: ["/bin/sh", "-c", "sleep 10 && pytest --disable-warnings"]


