name: Deploy Workflow
on:
  workflow_run:
    workflows:
      - Unit Tests
    types:
      - completed

env:
  PRIVATE_KEY: ${{ secrets.RSA_KEY_FOR_APP_EC2 }}
  INSTANCE_IP: ${{ vars.INSTANCE_IP }}

jobs:
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./python-fast-app
          file: ./python-fast-app/Dockerfile
          push: true
          tags: riyad2003/python-fast-app:v1

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ec2-user
          key: ${{ env.PRIVATE_KEY }}
          script: |
            # Ensure the directory exists
            if [ ! -d "/home/ec2-user/python-fast-app" ]; then
              mkdir -p /home/ec2-user/python-fast-app
            fi

            # Navigate to the directory where docker-compose.yml is located
            cd /home/ec2-user/python-fast-app

            # Check if docker-compose.yml is present
            ls -la

            # Pull the latest image (not necessary if already pulled)
            sudo docker pull riyad2003/python-fast-app:v1

            # Stop any running containers
            sudo docker-compose down || true

            # Pull the latest images as per docker-compose.yml
            sudo docker-compose pull

            # Start the containers in detached mode
            sudo docker-compose up -d

            # Clean up old Docker images
            sudo docker image prune -f