name: CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: ./python-fast-app
          file: ./python-fast-app/Dockerfile
          push: true
          tags: riyad2003/python-fast-app:v1
      - name: code check with pylint
        run: |
          cd ./python-fast-app
          pylint ./pyapp/*.py
    

