name: CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  code-check:
    name: check Python Code with Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Pylint
        run: |
          python3 -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint ./python-fast-app/*.py

  deploy:
    name: Build and Push Docker Image
    needs: code-check  # Ensure linting job runs successfully first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./python-fast-app  # Ensure the directory matches your repo structure
          file: ./python-fast-app/Dockerfile
          push: true
          tags: riyad2003/python-fast-app:v1

